// ============================================================
// BASE DE DATOS 2 - FRAME PERDIDO 
// ============================================================
var animes02 = [
    {
        id: 107,
        title: "Lucy, la hija del diablo",
        cover: "https://blogger.googleusercontent.com/img/a/AVvXsEgRCWkHYd_khpRUeGMyULNLo9VxHcPFMXzsYx5IPiTBcj9Bm6rHooV9Z7Xi5eoYXfD1KPANIjCqUSW_1aHGOx5EWuGtEymREIUjkwu3gYuyN_vCTu1Pj897yXPNrOqIZp0tk4FLd3RywNi558b7esJWWnFUeg3N7_C_0jBZkZJGde_i5d6anFGeyjW-1bMY=w272-h400",
        year: "2005-2007",
        type: "Serie TV",
        duration: "11 episodios (~12-15 min c/u)",
        studio: "Fluid Animation",
        director: "Loren Bouchard",
        genre: ["Comedia", "Animación para adultos", "Comedia negra"],
        tags: ["adult-swim", "comedia", "comedia-negra", "culto", "2000s", "animación", "absurdo", "loren-bouchard"],
        description: "Lucy es una chica de 21 años que vive en San Francisco y resulta ser la hija de Satanás. Su padre la ha elegido para que se convierta en el Anticristo, aunque a ella no le hace ninguna gracia y prefiere seguir con su vida normal, estudiando arte y saliendo con su novio, DJ Jesús. La serie sigue sus intentos por escapar de su destino demoníaco mientras lidia con su padre, un grupo de sacerdotes cazadores de demonios, y las absurdas situaciones que la rodean.",
        plot: "Lucy intenta vivir una vida normal en San Francisco mientras su padre, Satanás, insiste en que debe cumplir su destino como el Anticristo. Sus intentos por escapar de su legado se complican cuando se enamora de DJ Jesús, la segunda venida de Cristo. La serie mezcla situaciones absurdas, parodias religiosas y diálogos improvisados en un tono de comedia negra y surrealista.",
        analysis: "Lucy, la hija del diablo es una serie de culto de Adult Swim que combina el humor absurdo de Loren Bouchard con una premisa irreverente. La animación simple y los diálogos improvisados le dan un estilo único, similar a otras series del creador como Home Movies. A pesar de su corta duración (11 episodios), la serie logró crear una base de fans fieles, aunque nunca alcanzó la popularidad de Bob's Burgers. Es una obra para quienes buscan humor negro y parodia religiosa sin filtros.",
        forgotten: "A pesar de ser considerada una serie de culto por sus seguidores, Lucy, la hija del diablo es una rareza que el público general ha olvidado. Su corta duración (11 episodios) y el hecho de que Adult Swim no la renovara la condenaron al olvido. Hoy es más conocida por ser el 'prototipo' de Bob's Burgers que por sí misma, y solo los fans más acérrimos de Loren Bouchard o del Adult Swim de los 2000 la recuerdan. Una joya oculta para quienes buscan humor negro y parodia religiosa sin filtros.",
        trailer: "https://www.youtube.com/embed/2FjzP8h0VbY?si=7wJw7wJw7wJw7wJw",
        saga: null,
        sagaOrder: null,
        related: [89, 94, 92],
        category: "animada",
        origin: "Estados Unidos",
        rarity: "Raro",
        adulto: true,
        hentai: false,
        ecchi: false

    },
    {
    id: 108,
    title: "Fritz el Gato",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEi5lWBMDENqvUqD1rT8-SlPHVitNsp_PdOSAaOTPR5tVhmrVCr8wsl_JagwbjoXuInndmUfGBLy3mEAIChy05mP8D6VH2eOaEifnMwCUBm719YA77KYdbcYf1fqpGp59HX6ngxow6MtkkFfE4BCq1YpcR5X7XrQp6S8Ps7kayT1DjJdRU1bAODzpVLPD4k7=w237-h400",
    year: 1972,
    type: "Película",
    duration: "78 min",
    studio: "Bakshi Productions",
    director: "Ralph Bakshi",
    genre: ["Comedia", "Animación para adultos", "Sátira", "Contracultura"],
    tags: ["animación-adulta", "comedia", "sátira", "contracultura", "culto", "70s", "ralph-bakshi", "robert-crumb"],
    description: "Fritz es un gato de la universidad en la ciudad de Nueva York, un hipócrita, mujeriego y pseudointelectual que busca sexo, drogas y experiencias. La película sigue su viaje de 'auto-descubrimiento' a través del caos de la contracultura de los 60, desde una orgía en la bañera hasta un disturbio racial en Harlem, pasando por terroristas domésticos y una explosión en una central eléctrica. Una sátira social mordaz que se burla por igual de la derecha, la izquierda, los policías, los revolucionarios y los hippies.",
    plot: "Fritz, un gato estudiante universitario, vive su vida entre orgías, drogas y discursos vacíos sobre la revolución. Tras ser expulsado de la universidad, viaja a Harlem, donde provoca un disturbio racial. Luego se une a su exnovia en un viaje por carretera, donde se encuentra con terroristas domésticos que planean volar una central eléctrica. Sobrevive a la explosión y, en el hospital, aprovecha para seducir a tres enfermeras. La película es un retrato caótico y cínico de la América de los 70.",
    analysis: "Fritz el Gato es un monumento a la animación independiente. Fue la primera película animada en recibir una calificación X en Estados Unidos, rompiendo el molde de la animación familiar. Ralph Bakshi se inspiró en el cómic underground de Robert Crumb y creó una obra cruda, sucia y llena de sexo explícito, drogas y violencia. Su estilo innovador, que combinaba rotoscopia con fondos fotografiados, le dio una textura documental única. Fue un éxito rotundo, recaudando 90 millones de dólares frente a un presupuesto de 700.000. Sin embargo, el creador del personaje, Robert Crumb, odió la película y se desentendió de ella.",
    forgotten: "A pesar de ser un fenómeno en su época y la película de animación independiente más taquillera de la historia, Fritz el Gato ha quedado semi-olvidada. Su temática tabú y su estilo tan poco convencional la hicieron difícil de ver durante años, y hoy es una rareza de culto que sobrevive en la memoria de los amantes de la animación alternativa. Es un artefacto de una época, una reliquia de la rebelión que aún arde.",
    trailer: "https://www.youtube.com/embed/SY2qNNvX7kw?si=il-YbpzwSaf135YU",
    saga: "Fritz el Gato",
    sagaOrder: 1,
    related: [109],
    next: 109,
    category: "animada",
    origin: "Estados Unidos",
    rarity: "Raro",
    adulto: true,
    hentai: false,
    ecchi: false
},
    {
    id: 109,
    title: "Las nueve vidas de Fritz el Gato",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEhllo8V06Xlnb_w3TSNmsTOT3L4tAXvOgnomSgQzuudD5Al6h-4sRz1nHPtuDxyxqOekMjXJXtcTGXeDdRLclf-J0VStL8Z53PdPtMGnQ-CS9Zl41tbUrUYnd9G5ZpN3s3KBVhFWZ8Hq1NzbAF6nZpxtRga0ZmvW82lBbThbaU_mVv56EWW40VSe9AtBLjJ=w213-h400",
    year: 1974,
    type: "Película",
    duration: "77 min",
    studio: "Krantz Films / Cinemation Industries",
    director: "Robert Taylor",
    genre: ["Comedia", "Animación para adultos", "Sátira", "Antología"],
    tags: ["animación-adulta", "comedia", "sátira", "antología", "culto", "70s", "secuela"],
    description: "Esta secuela de Fritz el Gato se realizó sin la participación de Ralph Bakshi ni del creador del personaje, Robert Crumb. La película adopta un formato de antología, mostrando nueve vidas alternativas de Fritz en diferentes épocas y situaciones, desde la época de los conquistadores hasta el futuro. Una curiosidad histórica que fue la primera película animada en recibir una calificación R.",
    plot: "A diferencia de la primera película, esta secuela no sigue una narrativa lineal. En su lugar, presenta nueve historias independientes que exploran diferentes vidas que Fritz podría haber vivido. Cada segmento es una sátira de diferentes épocas y géneros, desde el western hasta la ciencia ficción. La película es un collage de humor absurdo y crítica social, aunque sin la cohesión ni la mordacidad de la original.",
    analysis: "Las nueve vidas de Fritz el Gato es una secuela que no cuenta con la participación de Ralph Bakshi ni de Robert Crumb, lo que la convierte en una rareza dentro de la franquicia. Fue el primer largometraje animado en recibir una calificación R en Estados Unidos. La película intenta replicar el éxito de la original con un formato de antología, pero carece del ingenio y la crudeza de la primera. Es una curiosidad histórica para los fans de la animación adulta, pero no alcanza el nivel de la obra de Bakshi.",
    forgotten: "Las nueve vidas de Fritz el Gato es la hermana olvidada de la franquicia. Sin la participación de Bakshi ni de Crumb, la película pasó sin pena ni gloria y hoy es una rareza que solo los coleccionistas más obsesivos conocen. Es recordada más por su contexto histórico (primera película animada con calificación R) que por su calidad. Una pieza de culto para completistas.",
    trailer: "https://www.youtube.com/embed/WVDFa2I1k1A?si=8qu6oZdtb3TTyTH4",
    saga: "Fritz el Gato",
    sagaOrder: 2,
    related: [108],
    prev: 108,
    category: "animada",
    origin: "Estados Unidos",
    rarity: "Muy raro",
    adulto: true,
    hentai: false,
    ecchi: false
},
    {
    id: 110,
    title: "Professor Pain (Gakuen Sodom)",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjHmLrF7qDtZn1U_bkAkyeGq3NtlViCZo8NhaDjbk9GNMD9mD-n5Vh0k7oVZrkOb1x0KYK59D8SHFtWnRCGeub3hjcriosD5YCN2YpSTEzb0IvAoiImDF36dlz9rE6y5JiAbxpperRWPOI2U4u7HqyiHzWOzTr4Bjpoj0dFL1Qg4OYUnbmYvpLE8ZwPAawm=w257-h400",
    year: 1998,
    type: "OVA",
    duration: "2 episodios (~27 min c/u)",
    studio: "Artland",
    director: "Kazuyoshi Yokota",
    genre: ["Terror", "Hentai", "Psicológico", "Violencia extrema"],
    tags: ["hentai", "terror", "violento", "gore", "psicológico", "culto", "90s", "rx", "adulto", "rareza"],
    description: "El profesor Ohse, aparentemente un pervertido, resulta ser un terrorista que toma como rehenes a las estudiantes de la Universidad Aoi con una bomba casera. Su objetivo es someter a las jóvenes a todo tipo de torturas y depravaciones para darles su 'lección especial'. Un OVA de culto extremo que mezcla terror y violencia con contenido sexual explícito.",
    plot: "En la Universidad Aoi, el profesor Ohse parece un acosador más. Pero cuando las estudiantes entran al aula, descubren que ha colocado una bomba casera y las ha tomado como rehenes. Ohse somete a las jóvenes a todo tipo de torturas y abusos sexuales mientras intenta darles su 'lección especial'. La serie explora los límites de la depravación humana y la violencia psicológica.",
    analysis: "Professor Pain (Gakuen Sodom) es un OVA hentai de culto que se inscribe dentro del subgénero de 'tortura y violación' tan popular en el mercado de animación para adultos de los 90. La obra intenta dar cierta profundidad al personaje del profesor, pero el desarrollo de los secundarios es limitado. Es una pieza de culto para coleccionistas de rarezas extremas, pero su contenido explícito la ha mantenido fuera del circuito mainstream.",
    forgotten: "Professor Pain es una rareza absoluta. Su distribución fue limitada y su contenido extremo la ha convertido en un producto de nicho. En España tuvo un doblaje realizado por el estudio K2000, pero hoy es prácticamente imposible de encontrar. Solo los coleccionistas más acérrimos de hentai de los 90 la recuerdan. Una pieza de culto para completistas.",
    trailer: "",
    saga: null,
    sagaOrder: null,
    related: [60, 61, 62],
    category: "animada",
    origin: "Japón",
    rarity: "Muy raro",
    adulto: true,
    hentai: true,
    ecchi: false
},
    {
    id: 111,
    title: "Inma Youjo: The Erotic Temptress",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjx72tLsnI5mmcEGzLZVF5eZUcoPiL33Tyq9CEx-A59k0NOUPKtUrYBCl5pKfM2iy4B3juTvb9Zr0181OMioyBxNJApmZqqGuHM3iZOQ2RD3Irb3ZbqiJDaSQfym8PbGG-TnUbnANzPRPq5SV4ljhudSmsJVR_KP9VI72frJuLckH2CFCJTtRtzrJZoB-VN=w280-h400",
    year: "1994-1997",
    type: "OVA",
    duration: "5 episodios (~30 min c/u)",
    studio: "Horannabi / Magic Bus / Pink Pineapple",
    director: "Varios",
    genre: ["Hentai", "Terror", "Psicológico", "Fantasía oscura", "Antología"],
    tags: ["hentai", "terror", "psicológico", "fantasía-oscura", "antología", "culto", "90s", "rx", "adulto", "rareza", "deconstrucción"],
    description: "Inma Youjo es una serie de culto del hentai de los 90 que se destaca por subvertir los tropos del género y contar historias con un trasfondo oscuro y complejo. La serie sigue a Maya, una figura enigmática descrita como una 'fuerza de la naturaleza' que siembra el caos y la destrucción allá donde va. Cada episodio presenta a una versión diferente de Maya en un mundo y época distinta, desde el cyberpunk hasta la caza de brujas en la Edad Media.",
    plot: "Maya es una entidad que viaja a través del tiempo y el espacio, apareciendo en diferentes épocas y lugares. En cada episodio, se encuentra con personas que sufren bajo el yugo del patriarcado, la opresión o la injusticia. Su presencia desata el caos y la violencia, pero también expone las verdades ocultas de cada sociedad. La serie es una antología que explora temas como el poder, el deseo, la violencia y la liberación, siempre desde un tono oscuro y trágico.",
    analysis: "Inma Youjo es una de las obras más interesantes y subversivas del género hentai. A diferencia de la mayoría de las series del género, que se centran en la fantasía sexual, Inma Youjo utiliza la violencia sexual y la explotación como herramientas para criticar el patriarcado y explorar temas de poder y deseo. La serie es una deconstrucción del hentai, que expone la misoginia y la violencia inherentes al género para ofrecer una experiencia incómoda y reflexiva. Cada episodio es una historia independiente con un estilo visual y narrativo diferente, lo que la convierte en una obra de antología única.",
    forgotten: "Inma Youjo es una rareza absoluta dentro del mundo del hentai. Su distribución fue limitada y su contenido extremo la ha convertido en un producto de nicho. A pesar de tener un lanzamiento en DVD por Critical Mass Video con doblaje al inglés, la serie es prácticamente desconocida para el público general. Solo los coleccionistas más acérrimos del hentai de los 90 la recuerdan. Una pieza de culto para completistas y amantes del terror psicológico.",
    trailer: "",
    saga: null,
    sagaOrder: null,
    related: [60, 61, 62, 110],
    category: "animada",
    origin: "Japón",
    rarity: "Muy raro",
    adulto: true,
    hentai: true,
    ecchi: false
}
        
];

