// ============================================================
// BASE DE DATOS - FRAME PERDIDO
// ============================================================
var animes = [{
    id: 0,
    title: "Barefoot Gen",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjMF-TZtwO2Jyhp2R3PKzwiJ0nQYuR6tI-QE3eyCdLjo1S8GFlm9GTw9UbqhVL1ZAX5L8JOPk31BtoJbEAVbpRzmYC9kEEMQfnL_KTX3IlqkcWO9VvDjw57rs1Jc9qrrShj9rSrjfbzSlHxntenQ1l1_bKLU5uHaPDXUGZqTEHpiGz4DYfNBblSahFT1CHf=w267-h400",
    year: 1983,
    type: "Película",
    duration: "85 min",
    studio: "Madhouse",
    director: "Mori Masaki",
    genre: ["Drama", "Histórico", "Bélico"],
    tags: ["drama", "histórico", "bélico", "melancólico", "violento"],
    description: "La historia de un niño que sobrevive al bombardeo atómico de Hiroshima. No es una película fácil de ver: es cruda, dolorosa y te deja sin aliento. Pero es necesaria.",
    plot: "Gen vive con su familia en Hiroshima durante los últimos días de la Segunda Guerra Mundial. El 6 de agosto de 1945, su vida cambia para siempre cuando la bomba atómica destruye todo lo que conoce. La película sigue su lucha por sobrevivir en un infierno de cenizas, cadáveres y radiación, mientras intenta encontrar a los pocos familiares que aún pueden estar vivos.",
    analysis: "Basada en el manga autobiográfico de Keiji Nakazawa, que perdió a su familia en el bombardeo. La animación de Madhouse es sencilla pero efectiva, y la historia te agarra del cuello y no te suelta. No es entretenimiento: es un testimonio. Una de las pocas películas de anime que debería ser de visionado obligatorio.",
    forgotten: "A pesar de ser una obra maestra, hoy es más conocida por su reputación que por haber sido vista. Su crudeza la ha convertido en una película que muchos evitan, y su distribución fuera de Japón fue limitada durante años. Es una de esas obras que todo el mundo conoce de nombre, pero pocos han tenido el valor de sentarse a ver.",
    reel: "https://video.fmga9-2.fna.fbcdn.net/o1/v/t2/f2/m412/AQOvjkLcaO4V4OdvsEhKTVkEGO8SJ1D8XqL7Oqo7B8xHgonQUTYFyEyapRRij0ZzoSSpIr4Tei1WrCJqAv7GXeeLNQmm1ueUpZWrIBd77A.mp4?_nc_cat=100&_nc_oc=Adp6gm0NdzHoGsQMk9jybSxOXgpQAsTxPjROaTanrxogleTrz-4jDWkBiIbaAQf6NhQ&_nc_sid=8bf8fe&_nc_ht=video.fmga9-2.fna.fbcdn.net&_nc_ohc=JaNq9qq8bWEQ7kNvwHzmMj0&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MTAyNjkzMjQxNjQ1OTE0MSwiYXNzZXRfYWdlX2RheXMiOjIxLCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6MTE4LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&_nc_gid=pzfC_bEBvVlQ9nECPgZ1sA&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQAqN7PY38Shz6Q40ijzP7FoEx9D-0PyYvEimU6V1Tcc3Q&oe=6A65A09E&bitrate=512006&tag=sve_sd",
    related: [1, 16, 18]
}, {
    id: 1,
    title: "Barefoot Gen 2",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjRwJcTh3oV7wpGSoRxUW_GJgtoiMc7_wx_r7RHjjVpQFS7PHX6ioqI0HuxiUkFWfklaKH76yWnlXOdUz8MMbE7i3RMGXHoTgf2Zbveakpfy3HEjav5Ck8mCoCjQEhsjEmG3p6BB5zZYQkall9MkxTfUn45mvMOSTNbjWlbaWks8hODUri9D0CUqsK1I-p9=w238-h400",
    year: 1986,
    type: "Película",
    duration: "85 min",
    studio: "Madhouse",
    director: "Toshio Hirata",
    genre: ["Drama", "Histórico", "Bélico"],
    tags: ["drama", "histórico", "bélico", "melancólico"],
    description: "Tres años después de la bomba, Gen sigue luchando por sobrevivir. Pero la guerra ha terminado, y ahora el enemigo es la miseria.",
    plot: "Han pasado tres años desde el bombardeo de Hiroshima. Gen vive con su madre y su hermano adoptivo en una chabola, sobreviviendo como puede. La película muestra las secuelas de la guerra: el hambre, la enfermedad, la discriminación a los supervivientes de la bomba (los 'hibakusha'), y la dificultad de reconstruir una vida cuando lo has perdido todo.",
    analysis: "Mientras la primera película muestra el impacto inmediato de la bomba, esta secuela se centra en sus consecuencias a largo plazo. Es igual de dura, pero de una manera más silenciosa y desgarradora. La animación es mejor que en la primera entrega, y la historia de Gen sigue siendo tan relevante como siempre.",
    forgotten: "Mucho menos conocida que su predecesora. La primera película tiene el impacto de mostrar el bombardeo, pero esta secuela es igual de importante para entender el verdadero horror de la guerra. Pasó desapercibida en su momento y hoy es una rareza incluso entre los fans del anime más clásico.",
    reel: "",
    related: [0, 16, 23]
}, {
    id: 2,
    title: "Plastic Little",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjDUAulBCVMTe7LK9nyBH-dtlaccK8gIPNkDAOJxlVeJCPVyxUt0QTX4jVvUUTJYPotrW6GUIvph9ysjv7joc7Ktvg3fFwExVOUPCSvB3AAImyAd5ER701FtZzuoyYviZcqJFTbqujSs93JuCZITP-1_JaZnd71mVAguD3cUyN8j6SQL0HczIYjtiJ54H4F=w288-h400",
    year: 1994,
    type: "OVA",
    duration: "47 min",
    studio: "AIC / Animate",
    director: "Kinji Yoshimoto",
    genre: ["Ciencia ficción", "Aventura", "Comedia"],
    tags: ["ciencia-ficción", "aventura", "comedia", "cyberpunk", "espacial"],
    description: "Tita es una cazadora de criaturas espaciales que protege a una misteriosa chica. Pero su verdadera misión es... ¿encontrar un buen chico?",
    plot: "Tita es la capitana de la nave 'Cha Cha Maru' y se gana la vida cazando bichos espaciales. Cuando rescata a Elysse, una fugitiva con un secreto, se ve envuelta en una conspiración que involucra a una secta religiosa, un dictador loco y un montón de naves con forma de... ¿pescado?",
    analysis: "Plastic Little es puro entretenimiento ochentero- noventero: acción, comedia, diseños de Satoshi Urushihara (con esos ojos y curvas que tanto le gustan) y una trama que no se toma en serio a sí misma. Es ligera, divertida y visualmente espectacular. La escena de la persecución en el mercado flotante es una joya de animación.",
    forgotten: "Nunca llegó a tener una gran franquicia. Es un clásico de culto para los que crecieron alquilando VHS en el videoclub. Su distribución fue limitada y, hoy en día, es una rareza que solo los coleccionistas más acérrimos buscan. Una pena, porque es de las OVAs más divertidas de los 90.",
    reel: "",
    related: [5, 20, 21]
}, {
    id: 3,
    title: "Big Wars",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEh5afmuycAaAShppiHCLIGwxyncXnHStD7iYZiADo40rDLxWw0rTvdwPTFIXQ_6SCWLMJXNBTQJC88d9xi9zYkiYszXT9myzn_UMhPqKSLbZ4hOGGtqgW_ZNa-V92grKpzKW069Cxo9KHg-MMOlXElvAnZEtS-SnsKVIeyaAZsvTeeHe7xzg-zodUtiq-Ce=w280-h400",
    year: 1993,
    type: "OVA",
    duration: "70 min",
    studio: "Magic Bus",
    director: "Toshifumi Takizawa",
    genre: ["Ciencia ficción", "Mecha", "Espacial"],
    tags: ["ciencia-ficción", "mecha", "espacial", "guerra", "acción"],
    description: "La humanidad coloniza Marte. Los alienígenas se hacen llamar 'Dioses'. Pero los humanos no son muy buenos creyentes.",
    plot: "En un futuro lejano, la humanidad ha colonizado Marte. Pero no están solos: una raza alienígena llamada 'Akushu' (que significa 'Dioses' en su idioma) los está atacando. La guerra espacial está servida, y el único hombre que puede detenerla es un piloto con más cojones que cerebro.",
    analysis: "Big Wars es pura ciencia ficción espacial de los 90: naves enormes, batallas épicas y una trama que intenta ser profunda pero se queda en el camino. La animación es decente, el diseño de mechas es chulo, y la música te pone en situación. No es una obra maestra, pero si te gustan las batallas espaciales, te va a encantar.",
    forgotten: "Su distribución fuera de Japón fue casi nula. Llegó en VHS a Estados Unidos de la mano de alguna distribuidora menor y desapareció. Es una de esas OVAs que solo los fans más hardcore del mecha conocen. Una joya oculta para los amantes de la ciencia ficción.",
    reel: "https://video.fmga9-3.fna.fbcdn.net/o1/v/t2/f2/m412/AQNuz_c6QMsBEEMKx3z6AspoWoFWkLYQOATxV9oFBw2v1F5Nz0PyiU_9w7lQ1zeXkVudMYjwtTb9bTSDJ1w0s2E02XoEI9xZxHEgE23rNQ.mp4?_nc_cat=110&_nc_oc=AdrxD5ol7Pd1nh_CWYdyWj7uq0baAwinlmhH0dDEIpJ2UYWMoF6V1DFDaTCHWKNwkhM&_nc_sid=8bf8fe&_nc_ht=video.fmga9-3.fna.fbcdn.net&_nc_ohc=DCkW_WUAQv0Q7kNvwGrPfSf&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MTUxMDg4MTc1MzMzMDI5NCwiYXNzZXRfYWdlX2RheXMiOjE3LCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6MTE3LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&_nc_gid=Tx8Kff8pv4nuF1OzsGbToQ&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQB37Jt3Yo_uCUDBSB15-BiVwxnI3V2wPb8m5o_zXQVi9g&oe=6A657748&bitrate=305927&tag=sve_sd",
    related: [5, 19, 20]
}, {
    id: 4,
    title: "Nineteen 19",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEhvly5x4_ftaet0n1igj1okjAtumrWdQqhwhk5p3Xq94xaCFCr2TlnFZ2ZsKc5hXxL8uzAOLPzJk10vk5XpWg6ASg0_kbh9JQ9raSy9MoH3WsvZPaQ6z5fNlrSJi6dPftI5EPe5Sw0Ly_OwMcquRrhEP7dzfgOILdyDziaM_z6-DUmTe5JQ8Zel5h1BgHn1=w309-h400",
    year: 1990,
    type: "OVA",
    duration: "42 min",
    studio: "Madhouse",
    director: "Koichi Chigira",
    genre: ["Drama", "Romance", "Recuentos de la vida"],
    tags: ["drama", "romance", "recuentos", "nostálgico", "melancólico"],
    description: "Kazushi tiene 19 años y busca el amor. Pero su primer amor vuelve a su vida, y todo se complica. Una historia de juventud, segundas oportunidades y la dificultad de crecer.",
    plot: "Kazushi es un estudiante universitario de 19 años que no tiene novia. Sus amigos le animan a encontrar una, pero él no tiene suerte. Cuando su primer amor de la infancia, Megumi, aparece de repente en su club, todo se revoluciona. Pero Megumi no es la misma chica que él recordaba, y Kazushi tendrá que enfrentarse a sus propios sentimientos.",
    analysis: "Nineteen 19 es un OVA romántico y melancólico de los que ya no se hacen. Madhouse demuestra que sabe hacer algo más que acción y violencia, con una historia sencilla pero bien contada. La animación es bonita, los personajes son creíbles y la música te atrapa. Ideal para una noche de domingo con una manta y una taza de té.",
    forgotten: "Es un OVA de romance puro, fácil de pasar por alto en una época dominada por el sci-fi y la acción. Además, su título genérico no ayuda a que la gente lo recuerde. Una joya escondida para los amantes del anime romántico.",
    reel: "https://video.fmga9-2.fna.fbcdn.net/o1/v/t2/f2/m412/AQNbobnd3IGEr5M1rC4Y8DyZBetg7Zpm5l_Ca112HSu_vuGURW4KfWikvcB8WjZoi5IlA32QqPcVb-tz646eXy4Psyj2x4X4eZnWIUFIoA.mp4?_nc_cat=103&_nc_oc=Adr2MUV6Hg8V2IZv08R3agK-M985CG67cTqEXcjohrKY1LjE2PHgC0H6J1ymbt8-Lng&_nc_sid=8bf8fe&_nc_ht=video.fmga9-2.fna.fbcdn.net&_nc_ohc=uD9ocIOI68IQ7kNvwFsR_Ti&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MjAxMDU4NDk3MzE3OTMxNywiYXNzZXRfYWdlX2RheXMiOjE5LCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6ODAsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=QMAilHvybEn_6EnJkSBIxQ&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQDP0YnDgkXbLR7dZQAZy2OzJyiZ7Cs5oSVpc-AkwRihdg&oe=6A656FEB&bitrate=174224&tag=sve_sd",
    related: [21, 16]
}, {
    id: 5,
    title: "Lily C.A.T.",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEhg_1kIOwslOhHS9gQYx3L1fk5zQBZKdDgiq9C0IKkrMDQh2mUmb0MO1M5KCXnNW7PryIW5Tyoe7BcmhIifte0-PUZQtHBVH0ofwke8TJRetQLEH1KjH0iMjUyDaei1tHo70xHVk_tdLJM2rk-3x6nNXoAyhHybDFH0S5Fu4UWzwKNAf8zlDf5lEJQNysvd=w242-h400",
    year: 1987,
    type: "Película",
    duration: "67 min",
    studio: "Studio Pierrot",
    director: "Hisayuki Toriumi",
    genre: ["Ciencia ficción", "Terror"],
    tags: ["ciencia-ficción", "terror", "espacial", "nocturno", "claustrofóbico"],
    description: "Imagina Alien, pero hecho en Japón, con menos presupuesto y un gato espacial. Lily C.A.T. no reinventa la rueda, pero te hace sentir que estás dentro de una nave condenada, y eso ya es suficiente.",
    plot: "En el siglo XXIII, la nave Saldes viaja con una tripulación mixta de personal de la compañía Syncam y oficiales de la nave. Cuando el ordenador detecta desechos espaciales y los recoge, una bacteria extraterrestre se libera. Los pasajeros empiezan a morir de una infección misteriosa que disuelve sus cuerpos pero deja la ropa intacta. Pronto descubren que la bacteria evoluciona rápidamente y puede imitar la forma de sus víctimas. Mientras los supervivientes luchan por mantenerse con vida, se revela que dos de los pasajeros son impostores: un asesino y un detective que lo persigue. Pero el verdadero enemigo es Lily C.A.T., un robot con forma de gato que ha tomado el control de la nave.",
    analysis: "Lily C.A.T. es una carta de amor al terror espacial de los 80, con claras influencias de Alien y La Cosa de John Carpenter. La animación es tosca pero efectiva, y el diseño de la criatura es obra de Yoshitaka Amano, el legendario artista de Vampire Hunter D y Final Fantasy. Tiene un toque de serie B que le da encanto, y la trama, aunque predecible, se sigue con interés. La banda sonora de Akira Inoue crea una atmósfera opresiva que te atrapa desde el primer minuto.",
    forgotten: "Lily C.A.T. fue víctima de su título extraño y su distribución limitada. La versión en inglés fue producida por Carl Macek (el responsable de Robotech) y distribuida por Streamline Pictures, pero la compañía quebró y los derechos quedaron en el limbo. Hoy es un objeto de culto para los coleccionistas de OVAs de terror espacial, pero el público general ni siquiera sabe que existe. Una joya oculta que merece ser rescatada.",
    reel: "https://video.fmga9-3.fna.fbcdn.net/o1/v/t2/f2/m412/AQOLANgIVFHntlbrwUjArmXNh-D-NzfA2bKRTDwxtBy2AzXYBgT2k5hTiRsySLbo28U4QRl0kq3OTmG8mzCcbYId-6eFnMVGA7DLhwVdig.mp4?_nc_cat=111&_nc_oc=AdohpFc-ESsIchkW1JAeSzTVAtunPtaCOFab0LCfZsBo28WgVnBe2nWM_slDxlZKd1o&_nc_sid=8bf8fe&_nc_ht=video.fmga9-3.fna.fbcdn.net&_nc_ohc=ay_sY3jbeCIQ7kNvwHi0bb5&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MjA4ODcwMTAxMjUyNzA5NCwiYXNzZXRfYWdlX2RheXMiOjE5LCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6NzksInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=EN7YQAP3vhRjGmjrsqUkFQ&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQCPqoiiciUrazn35BoXMKxguqaQ0dMiDdLK983EQL1caQ&oe=6A657C8F&bitrate=275515&tag=sve_sd",
    related: [8, 11, 3]
}, {
    id: 6,
    title: "Roots Search",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjLmo4GWpgI-0G-EieWHr0M0kA6lBsL4aIkrDia6-uB0Qkt1WqdttQgy9L-iI_fK2_Td-OS-zK1IaEXKtvdaF5tWARVRbBFhhTqGd0AVpXrNqbHXLaC3HPgwnDUnorr68jXlk1mzzY70jRVmgh971VlIlwan4YpheRF-3NeOnr8pWdHhgnsm1C2ZXhX70Gn=w400-h300",
    year: 1986,
    type: "OVA",
    duration: "45 min",
    studio: "Desconocido",
    director: "Desconocido",
    genre: ["Ciencia ficción", "Terror", "Horror espacial"],
    tags: ["ciencia-ficción", "terror", "espacial", "nocturno", "claustrofóbico", "experimental"],
    description: "Un equipo de investigación encuentra una nave abandonada. Algo han traído a bordo. Algo que no debería haber salido de ahí.",
    plot: "Un equipo de investigación espacial encuentra una nave desierta. Pero no está vacía: algo se ha quedado dentro, y ahora ha viajado con ellos. La tripulación empieza a morir de manera extraña, y el horror se apodera de la nave. ¿Qué es lo que han traído a bordo? ¿Y cómo pueden detenerlo antes de que sea demasiado tarde?",
    analysis: "Roots Search es el ejemplo perfecto de OVA de terror espacial de serie B. Tiene el encanto de las películas de terror de los 80: efectos especiales cutres, una trama que no se toma demasiado en serio, y una atmósfera de claustrofobia que te atrapa. La animación es limitada, pero la historia tiene un ritmo ágil que te mantiene pegado a la pantalla.",
    forgotten: "Roots Search es el ejemplo perfecto de OVA que pasó sin pena ni gloria. Nunca tuvo una distribución internacional decente, y hoy es una rareza que solo los coleccionistas más obsesivos conocen. Su título genérico y su portada cutre no ayudan a que la gente la recuerde. Una joya oculta del terror espacial.",
    reel: "",
    related: [5, 11, 7]
}, {
    id: 7,
    title: "Midori: La Niña de las Camelias",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEg0FowtbPx2odlroSexKy_AlwHsWU3HbnWdUMMXMax0yIQGsmx1-jDlnBsqoI26zgj6s6jRN_rBvnzH5ldbzgyuDM_xKf_0T3Ooa3Bt7g2ao1ZF55rl3hA9mfDfg7A95Wrz1RaThwgROIFBWpfz-NGeXSIGeMGEDkOHXWNOgznRriWikwtp2qD0QqRQJpzS=w270-h400",
    year: 1992,
    type: "Película",
    duration: "56 min",
    studio: "Harada Production",
    director: "Hiroshi Harada",
    genre: ["Drama", "Terror", "Psicológico", "Ero-guro"],
    tags: ["drama", "terror", "psicológico", "violento", "experimental", "nocturno"],
    description: "Midori no tiene nada. Ni padres, ni dinero, ni esperanza. Cuando el dueño de un circo de fenómenos la recoge, cree que es su salvación. Pero el circo es un infierno de carne y miseria, y ella es la nueva atracción.",
    plot: "En el Japón de la posguerra, Midori queda huérfana y es acogida por el dueño de un circo ambulante. Pronto descubre que el circo no es más que una fachada: sus integrantes son fenómenos de feria, marginados y sádicos, que la someten a todo tipo de abusos. Midori busca desesperadamente una salida, pero el circo es un laberinto sin puertas. Su única aliada es una enana que también sufre, pero incluso la amistad es frágil en este mundo de pesadilla. El final es uno de los momentos más perturbadores de la historia del anime.",
    analysis: "Midori es una obra que no debería existir. Y sin embargo, existe, y es una maldita obra maestra. Hiroshi Harada pasó 5 años dibujando a mano cada fotograma, con un nivel de detalle que duele. La animación es hipnótica, los colores son vibrantes y la banda sonora es de una belleza cruel. Pero la historia es un puñetazo en el estómago: abuso, degradación, violencia, y un final que te deja con el alma en carne viva. No es para estómagos sensibles, pero es una obra de arte que no se puede ignorar. Es el 'Saló' del anime.",
    forgotten: "Midori fue censurada en Japón antes de su lanzamiento. El gobierno consideró que era 'peligrosa para la moral pública' y ordenó destruir las copias. Harada la proyectó en un solo cine durante una semana antes de que la prohibieran. Pero la historia es aún más oscura: algunas personas entraron en su casa, robaron parte del metraje y destruyeron escenas, por lo que Harada tuvo que reemplazar algunas con fotos y acortar la película. Las copias que sobrevivieron circularon en el circuito underground durante décadas. Hoy es un objeto de culto, pero también un recordatorio de que el anime puede ser tan oscuro como el alma humana.",
    reel: "https://video.fmga9-2.fna.fbcdn.net/o1/v/t2/f2/m412/AQPV9akZDJposK44RAQaTSFKAfmd1PX8h_jEuG-bnYcUXGEY5hTdn7tJKhwdoQ3-SsuZP6CN5Go9-eBcbeKPTfgqYACh2qMGwGiNc1x_-g.mp4?_nc_cat=105&_nc_oc=AdpUgbz488xblZ2orq-ymb09P39tHeK9JudPqz0rfdXXpHvPXGErb-ANKcvNXkBWOfg&_nc_sid=8bf8fe&_nc_ht=video.fmga9-2.fna.fbcdn.net&_nc_ohc=R2KLDoJ10usQ7kNvwG9_66-&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6OTc0MzQ4OTQyMjcwNjYzLCJhc3NldF9hZ2VfZGF5cyI6MjQsInZpX3VzZWNhc2VfaWQiOjEwMTIyLCJkdXJhdGlvbl9zIjoxMDMsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=27osSeu5750_FRxBuuKc7w&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQDXyWs_H5Ru_5RBd8W_Amvrwu63pgMvyJ8LNr6oQQDZtA&oe=6A6579B1&bitrate=302525&tag=sve_sd",
    related: [10, 9]
}, {
    id: 8,
    title: "MD Geist",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjFOROHRO0UHSyf-1qnUt06Yez7sKvJia5xbrp1YdK_Igdkxqdo1u89LzRnxJoMJ1KGSu_3I9rvE5iozYqG1Jq3NCtoQVsMJjSkkSUPPTrY15jlnJVvjvQ4G7O_GCX0ThGiS9b7mwUPlh3km6x0kC6eQnyyUfG69dyFWrgAoep4xVKwH2ToMzaGo-VSNVq8=w227-h400",
    year: 1986,
    type: "OVA",
    duration: "44 min",
    studio: "Nippon Columbia",
    director: "Hayato Ikeda",
    genre: ["Ciencia ficción", "Acción", "Mecha"],
    tags: ["ciencia-ficción", "acción", "mecha", "violento", "guerra"],
    description: "Geist es un soldado mejorado genéticamente con una insaciable sed de batalla. No es un héroe. Es una máquina de guerra.",
    plot: "En un futuro post-apocalíptico, el soldado Geist despierta de su congelación criogénica. Es un M.D.S. (Most Dangerous Soldier), una máquina de matar creada para la guerra. Pero la guerra ha terminado, y ahora Geist no tiene propósito. Hasta que descubre que el planeta está bajo el control de un dictador loco, y decide que la única solución es... más guerra.",
    analysis: "MD Geist es el prototipo de OVA de acción de los 80: violencia sin concesiones, un protagonista que es más bestia que persona, y una trama que apenas se sostiene. Pero es tan exagerado, tan ridículo y tan violento que resulta entretenido. Es la versión anime de las películas de acción de los 80, con todo lo bueno y lo malo que eso conlleva.",
    forgotten: "Nunca llegó a ser tan popular como otras series del género. Su protagonista es un psicópata, la violencia es excesiva y la trama es casi inexistente. Es una OVA de culto para los que buscan acción pura y dura, pero el público general la ha olvidado. Una rareza que solo los fans del mecha más hardcore recuerdan.",
    reel: "https://video.fmga9-3.fna.fbcdn.net/o1/v/t2/f2/m412/AQPDdpaug0HJypGQVzQiGz2HvW6FOklWlmE0TEMIWEBKUCh_wuOI06m0Akp2f539eEJl7dgK-uiwR6s0k_uyIb0tRPR276hcBI4zt4IK-w.mp4?_nc_cat=110&_nc_oc=AdpMHL2mAdZz-MJbzLHsboTKcafVTu2IBBk2BPqFUux3bWejksoHc9h-HG88BKuOf70&_nc_sid=8bf8fe&_nc_ht=video.fmga9-3.fna.fbcdn.net&_nc_ohc=loXPRiSxBCsQ7kNvwHoKFDI&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MjcyNDMzNTA5OTUzMDY1MjcsImFzc2V0X2FnZV9kYXlzIjoyNSwidmlfdXNlY2FzZV9pZCI6MTAxMjIsImR1cmF0aW9uX3MiOjE0MSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&_nc_gid=FNP8kHOoUN54s6VnPGqnZA&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQCO-Y3g2ciNUn42TTDb3_wA9h0LD9gxKnXEFiKp1Da_ig&oe=6A657738&bitrate=274037&tag=sve_sd",
    related: [10, 12, 20]
}, {
    id: 9,
    title: "Hell Target",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjmEGaiC9GNaVrbiYsPTQgbnm38fv87wVL0GOWIj8QvWN_y6zJxy0mTZr8-2m_t08iAeuhnazNo7rSBOzae_nX6TsA1XzzezhEvq5xC_noEELYRNGQe1oMWyfrpQ1nIUZyjN-9RXOvXs3m5c2Y53o7vLcMmkEoqpb0x2OpBHu2HsZ_cyyhTZB2mMjjNje6h=w222-h400",
    year: 1986,
    type: "OVA",
    duration: "50 min",
    studio: "Nakamura Production",
    director: "Keizo Nakamura",
    genre: ["Ciencia ficción", "Terror", "Horror espacial"],
    tags: ["ciencia-ficción", "terror", "espacial", "nocturno", "claustrofóbico"],
    description: "Un equipo de exploración en un planeta infernal descubre un secreto terrorífico. Y el secreto, como siempre, quiere matarlos.",
    plot: "En el planeta Inferno II, un equipo de exploración encuentra una nave abandonada. Pero no está vacía. Una amenaza alienígena se despierta y empieza a matar a la tripulación uno por uno. La única esperanza es descubrir qué es lo que están enfrentando antes de que sea demasiado tarde.",
    analysis: "Hell Target es otra OVA de terror espacial de los 80, con el mismo ADN que Lily C.A.T. y Roots Search. Tiene el encanto de las películas de terror de serie B, con una animación limitada pero efectiva, y una trama que no se toma demasiado en serio. Es el tipo de OVA que veías a las 2 de la madrugada en el videoclub y no podías parar de ver.",
    forgotten: "Es una de esas OVAs que solo existieron en VHS. Nunca tuvo una distribución internacional decente, y hoy es una rareza que solo los coleccionistas más obsesivos conocen. Una joya oculta del terror espacial que merece ser rescatada.",
    reel: "https://video.fmga9-2.fna.fbcdn.net/o1/v/t2/f2/m412/AQMX6_MKhmByEXhLUWv04le_sQPqA91OQ4k0QAPDVQDQXbXrYPpGU3On4iV8ebsdLTvNHNilVwGtaEkHrdDrZNr8BX2eVQoQlWhwKacmbg.mp4?_nc_cat=104&_nc_oc=AdrWEqRvvdPsw0D0tHrBvn3yS9ysPOwDScB3ksa7P5mN9n-MVaCVp_mRdtV-yjHhmTk&_nc_sid=8bf8fe&_nc_ht=video.fmga9-2.fna.fbcdn.net&_nc_ohc=PMOIXvxtWGMQ7kNvwHIujAt&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6OTkyNzI3MDIwMDcxNDYxLCJhc3NldF9hZ2VfZGF5cyI6NDksInZpX3VzZWNhc2VfaWQiOjEwMTIyLCJkdXJhdGlvbl9zIjo2NCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&_nc_gid=vzQXnmo2whrS2IpO0pf2tg&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQAf3nL66BlPq_q3PhJGbPLM3qfxGQLzNSrkAjBC9WeSOA&oe=6A659892&bitrate=213483&tag=sve_sd",
    related: [5, 6, 8]
}, {
    id: 10,
    title: "Ninja Resurrection",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEhzVyH8GPj2zEsTTwenXH7GUlI76D_eFYivEr2BiSV0FqXttCfOUgh5aa0zZkM5yLqTuL9xwAeniYoKxI659OOTlntwb0vxFPScY7MiQKVRTctbBDKTmG3zJaQZg5hHuMnHd-JsKlKRxoo_FgIFyGAyQheAT0QuJ-Q2PlSi7igVFhBpKp2lkotBMUasVDjY=w283-h400",
    year: 1997,
    type: "OVA",
    duration: "70 min (2 episodios)",
    studio: "J.C.Staff",
    director: "Yasunori Urata",
    genre: ["Acción", "Fantasia oscura", "Histórico"],
    tags: ["acción", "fantasía", "histórico", "violento", "nocturno", "samurái"],
    description: "Amakusa Shiro, el líder de una rebelión cristiana, resucita con poderes sobrenaturales. No es un santo. Es un demonio.",
    plot: "En el Japón del siglo XVII, Amakusa Shiro lidera una rebelión cristiana contra el shogunato. Es derrotado y ejecutado. Pero no muere. Resucita con poderes demoníacos, y su venganza es más aterradora que su vida. Ninjas, samuráis y monjes se enfrentan a una amenaza sobrenatural que podría destruir Japón.",
    analysis: "Ninja Resurrection es pura acción de los 90: violencia exagerada, un protagonista que es más bestia que humano, y una trama que apenas se sostiene. La animación es decente, y las escenas de lucha son coreografiadas con un ritmo trepidante. Pero la historia es confusa y los personajes son planos. Es el tipo de OVA que ves por la acción, no por la historia.",
    forgotten: "Solo se hicieron dos episodios de los cuatro planeados. La serie fue cancelada por bajo presupuesto o falta de interés, y nunca se completó. Es una rareza para los fans del anime de acción, pero el público general la ha olvidado. Una OVA que prometía y no cumplió.",
    reel: "https://video.fmga9-2.fna.fbcdn.net/o1/v/t2/f2/m412/AQMuCfABFaWNYtEq1SXTt6H1GxlRyQWWGGggx2TCS9dyebfSoOeUmGZEiHldxjrjFAI0bDRbMtl2LYaNATM_zU29gl54u1BJXfCVvZJy4g.mp4?_nc_cat=102&_nc_oc=AdrCzSDg8fwcxeqK15jYCTQZguCpTQ7-VfeLX1vSpmecIDczQVkzsY4vXr0VY8CC5IE&_nc_sid=8bf8fe&_nc_ht=video.fmga9-2.fna.fbcdn.net&_nc_ohc=iYpGWUW47SgQ7kNvwGj1cMk&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MjIzMjg1MzAxMDg2Mzg5MCwiYXNzZXRfYWdlX2RheXMiOjUwLCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6NzcsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=NKB7KFDnrHaoZwGjIOvjeA&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQD6VRWrHwenwPSGDdymRFF8fIFKyydCsEf18ObyPnZO9Q&oe=6A658574&bitrate=222128&tag=sve_sd",
    related: [8, 12, 13]
}, {
    id: 11,
    title: "Battle Royal High School",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEj9JcKCaMVHWzlMiDfKsNu3TSNBq-V8P-CSGtFzIsKeRxPdGVFz9_ZYpTrxw87QY-xrKhKRm6ofS-I-X5xZRHFURWFpxVKyphkFyFVgJE0qtdg2Catc_pAXzrHgBF6VtikeuOQm3uq56LfXqcGT-4o0bhgiSKs1-T4cpoBOE_QEuNIZsr2c23HJ3m9p72Em=w258-h400",
    year: 1987,
    type: "OVA",
    duration: "60 min",
    studio: "DAST",
    director: "Ichirō Itano",
    genre: ["Acción", "Fantasía oscura", "Artes marciales"],
    tags: ["acción", "fantasía", "artes-marciales", "violento", "nocturno"],
    description: "Un instituto donde los estudiantes son guerreros y los demonios acechan. La clase de lucha no es una asignatura, es cuestión de vida o muerte.",
    plot: "En el instituto de la ciudad de Tokio, los estudiantes son entrenados en artes marciales para defenderse de los demonios que acechan en las sombras. Pero cuando una invasión demoníaca amenaza la ciudad, los estudiantes se convierten en la última línea de defensa. El problema es que algunos de ellos no son tan humanos como parecen.",
    analysis: "Battle Royal High School es pura acción de los 80: artes marciales, demonios, estudiantes y una trama que apenas se sostiene. La animación es decente, y las escenas de lucha son coreografiadas con un ritmo trepidante. Es el tipo de OVA que ves por la acción, no por la historia. Un clásico de culto para los fans del anime de acción.",
    forgotten: "Su distribución fuera de Japón fue muy limitada. Nunca llegó a tener el éxito de otras series del género, y hoy es una rareza que solo los coleccionistas más obsesivos conocen. Una joya oculta para los amantes de la acción.",
    reel: "https://video.fmga9-3.fna.fbcdn.net/o1/v/t2/f2/m412/AQPOTQ3McHbjlDIMgPNmFirizkaQMNyGCL31scwXPQpoi9B5cMB3UbeaOsv5uZPKZN2puVvOVywks5WrOgFlb3E7MfwC2z0VksPywxe-DA.mp4?_nc_cat=109&_nc_oc=AdqVb88xTCPGk9skUCvZPuosv7MT_dYJE8BoFe5_MqLk-91hy_EeW0rG_7TiEFjEKt4&_nc_sid=8bf8fe&_nc_ht=video.fmga9-3.fna.fbcdn.net&_nc_ohc=QXgWq3gLUmsQ7kNvwFiPW7Q&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MjA0NzA5NTEzOTI0OTYyOSwiYXNzZXRfYWdlX2RheXMiOjU1LCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6NzIsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=5P9lkars0hoVf119K__3yQ&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQCeazsoZaE6m_FVu_Ngil_D94hHzj-lMdnlj4vNGaxcgQ&oe=6A6579E5&bitrate=302968&tag=sve_sd",
    related: [10, 12, 14]
}, {
    id: 12,
    title: "Fatal Fury (Películas)",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjrEuTeh3tVg9ryum6QeQkJN6xazYf89Z7oNK-eBajqyKP0uNIJMGj1uwonOZDa6JYh-TqhXU5ClWjL9Y_tffLnvpaY8WW_d9KljrTH3FXDFpQ8yIpm0VNLtT-SJdSWNe-kRvCYGZjdyeJo2FGeywatI9dtyXE9e2v3UDEU31HBmJbZmgPiI3NDg5RyN9Rn=w267-h400",
    year: "1992-1994",
    type: "Películas",
    duration: "45 min / 65 min / 90 min",
    studio: "Studio Comet",
    director: "Kazuhiro Furuhashi",
    genre: ["Acción", "Artes marciales", "Videojuego"],
    tags: ["acción", "artes-marciales", "videojuego", "violento"],
    description: "Las tres películas de Fatal Fury: Legend of the Hungry Wolf (1992), The New Battle (1993) y The Motion Picture (1994). Terry y Andy Bogard buscan venganza contra Geese Howard, luego enfrentan a Krauser y finalmente viajan por el mundo para detener a Laocorn.",
    plot: "La saga de Fatal Fury sigue a los hermanos Bogard en su lucha contra el crimen organizado y guerreros legendarios. Desde el torneo King of Fighters hasta batallas épicas contra poderosos enemigos.",
    analysis: "Fatal Fury es una adaptación del famoso videojuego de SNK. La trilogía muestra la evolución de la animación y las historias, desde la venganza contra Geese Howard hasta aventuras más ambiciosas.",
    forgotten: "Su corta duración y lanzamiento directo en VHS las convirtieron en un producto de nicho. Hoy son una rareza que solo los fans más acérrimos de Fatal Fury recuerdan.",
    reel: "",
    related: [8, 10],
    episodios: [
        { num: 1, title: "Legend of the Hungry Wolf", year: 1992, desc: "Terry y Andy Bogard buscan venganza contra Geese Howard en el torneo King of Fighters." },
        { num: 2, title: "The New Battle", year: 1993, desc: "Terry es derrotado por Krauser y cae en el alcoholismo." },
        { num: 3, title: "The Motion Picture", year: 1994, desc: "Terry, Andy y Joe viajan por el mundo para detener a Laocorn." }
    ]
}, {
    id: 13,
    title: "Blood Reign: Curse of the Yoma",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjWkvxDkHIT4TpCww5XxY1l4NczleJ6qRFRnHJnmki4zuuiCWPdf_yyYzcm5hImIQFh9b2dAckEGf4TKHUb-LvFY3GPxpVu_91BTYxYkavLGjptHHDBrW1ZdS1aMybybJuy7HZHwBdYmrY3Iv50jjDjim86rFRH8KnMR45udUDdWoECiRTaKSAhuw1U-Iee=w265-h400",
    year: 1989,
    type: "OVA",
    duration: "2 episodios (45 min c/u)",
    studio: "J.C.Staff",
    director: "Takashi Anno",
    genre: ["Acción", "Fantasía oscura", "Terror", "Samurái"],
    tags: ["acción", "fantasía", "terror", "samurái", "violento", "nocturno"],
    description: "Un ninja llamado Hikage debe detener a su antiguo amigo, ahora poseído por un demonio, antes de que destruya el mundo. Una historia de violencia, amistad y demonios.",
    plot: "Hikage es un ninja que debe enfrentarse a su antiguo amigo, que ha sido poseído por un demonio. La batalla se intensifica cuando otros demonios comienzan a aparecer, y Hikage descubre que la única forma de salvar a su amigo es viajar al mundo de los muertos. Pero el viaje será más peligroso de lo que imagina.",
    analysis: "Blood Reign es una OVA de horror y acción de los 90. La animación es oscura y gore, y la historia es una mezcla de tragedia y violencia. Es una obra que muestra lo mejor del anime de terror de la época.",
    forgotten: "Es una OVA que pasó desapercibida en su momento. Su distribución fuera de Japón fue limitada, y hoy es una joya oculta para los amantes del horror y la fantasía oscura.",
    reel: "",
    related: [8, 10, 15, 20]
}, {
    id: 14,
    title: "Angel's Egg",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEgpT1jNuTzFcNGlvP_d5_lDHHjtMW9ePw0DpS16mswMMzTqk3u1OlMW2lhq_IoSAebh45mPk-MSfChKGFVNZu7sf5pcgaz8LzzxkxcR1rvAE_ry1wG_Ahe1XC5dxZD9glLS17d2FzWf8CPkACqn8L3P20xE1jiFNi3hpmhwypLfyDwTBQfsio6YxxgdYqsc=w273-h400",
    year: 1985,
    type: "OVA",
    duration: "71 min",
    studio: "Studio Deen",
    director: "Mamoru Oshii",
    genre: ["Fantasía", "Ciencia ficción", "Experimental"],
    tags: ["fantasía", "ciencia-ficción", "experimental", "melancólico", "nocturno", "silencio"],
    description: "En un mundo gris, sin sol, sin esperanza, una niña camina con un huevo. No sabemos qué hay dentro, pero ella lo protege como si fuera su propia vida. Un soldado la sigue, fascinado, y juntos se adentran en una pesadilla visual donde las sombras tienen más peso que las palabras.",
    plot: "Una niña anónima protege un huevo enorme en un mundo sombrío y devastado. Un soldado con una cruz en la espalda la encuentra y decide seguirla. Juntos recorren una ciudad en ruinas, un mar de piedra y árboles petrificados. Mientras ella protege su huevo, él busca respuestas que nunca llegan. El final te dejará sin aliento.",
    analysis: "Angel's Egg es lo que pasaría si Tarkovsky hiciera anime. Mamoru Oshii (Ghost in the Shell) se alió con Yoshitaka Amano (Final Fantasy) para crear una obra que desafía toda lógica narrativa. No hay diálogos importantes, no hay explicaciones, solo imágenes que te perforan la retina: peces gigantes volando, sombras que caminan solas, una niña que no habla y un huevo que podría serlo todo o nada. Es una experiencia religiosa, onírica, y profundamente melancólica. La banda sonora de Yoshihiro Kanno te atrapa y no te suelta hasta que los créditos pasan. No es para todos, pero los que la entienden la llevan tatuada en el alma.",
    forgotten: "Angel's Egg nació muerta comercialmente. Oshii la hizo como un experimento personal, sin pensar en el público. En Japón se proyectó en una sola sala de cine y desapareció. Nunca tuvo lanzamiento en VHS en Occidente, solo circuló en copias piratas y grabaciones de televisión. Su rareza la convirtió en leyenda entre coleccionistas, pero el público general ni siquiera sabe que existe. Hoy es un fantasma que algunos buscan con desesperación.",
    reel: "",
    related: [16, 18, 24]
}, {
    id: 15,
    title: "Riki-Oh: The Wall of Hell",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEiORmSHwWGi3oHEFUMWIPqTD3U5fmIaA2TKUBNrafC-9oz4wHNVtIZfbtElebq7duDfo8JgV5DFLiXexpxKv_xmmF4ILY41KHs2DA2n3S-5jPryyIKFKYy-jCwBRE6LTtjZeHfSQtYVwMXTt2lykggD6f0XL-xkIrFu7E8tyJnbq_NHBtDQQ-AgXj3pqb2S=w300-h400",
    year: 1989,
    type: "OVA",
    duration: "50 min",
    studio: "J.C.Staff",
    director: "Satoshi Dezaki",
    genre: ["Acción", "Artes marciales", "Violencia"],
    tags: ["acción", "artes-marciales", "violento", "gore", "experimental"],
    description: "Riki-Oh es un hombre con fuerza sobrehumana. Está en una prisión privada, rodeado de mafiosos y asesinos. Pero no es un preso cualquiera: es una máquina de matar.",
    plot: "Riki-Oh es un artista marcial con fuerza sobrehumana. Tras ser encarcelado injustamente en una prisión privada, descubre que los guardias y los presos están controlados por la mafia. Riki-Oh decide tomarse la justicia por su mano, usando sus habilidades para sobrevivir y enfrentarse a los criminales que lo rodean.",
    analysis: "Riki-Oh es la adaptación del manga más violento. La violencia es exagerada hasta el absurdo: Riki-Oh arranca cabezas, parte cuerpos y destroza todo a su paso. Es una obra de culto para los amantes del gore, pero no es para todos los públicos. La animación es limitada, pero las escenas de lucha son coreografiadas con un ritmo trepidante.",
    forgotten: "Fue tan extremo que su distribución fue muy limitada. La censura y la violencia excesiva la convirtieron en un producto de nicho, y hoy es una rareza que solo los fans más hardcore del gore conocen. Una joya oculta para los amantes de la violencia.",
    reel: "",
    related: [8, 10, 12]
}, {
    id: 16,
    title: "Roujin Z",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEh9Qev2nFRnA3_XenbFLGXuzxoFMoz1DGAEb11LPKtaTeTTGa8osVTUx2Hg01JWsiI-deTwmvXp0OsTnGta4Ql0Urf2UOXQtKABn5ePPM7FxSiFbx_f2svogjUfnMYqbwOBkeEbqk2jetpPCwh-2KurEATFFz7PohG8w9R0UWe1_0mAG8L6ZnyA9453tq6w=w283-h400",
    year: 1991,
    type: "Película",
    duration: "80 min",
    studio: "A.P.P.P.",
    director: "Hiroyuki Kitakubo",
    genre: ["Ciencia ficción", "Comedia", "Sátira"],
    tags: ["ciencia-ficción", "comedia", "sátira", "robot", "nostálgico"],
    description: "Un robot de cuidados para ancianos se vuelve loco. No es una historia de terror, es una comedia. Y es una de las sátiras más inteligentes del anime.",
    plot: "El robot Z-001 es un androide diseñado para cuidar de ancianos. Pero cuando se vuelve loco, decide que el mejor cuidado para su anciano es... llevárselo a la playa. Mientras el gobierno intenta detenerlo, una estudiante de enfermería y un grupo de ancianos se unen para proteger al robot. Una comedia de ciencia ficción que no te dejará indiferente.",
    analysis: "Roujin Z es una sátira divertidísima sobre el envejecimiento, la burocracia y la tecnología. La animación es excelente, y la historia está llena de momentos hilarantes y otros más emotivos. Es una película que te hará reír y reflexionar a partes iguales. Una joya del anime de los 90.",
    forgotten: "No tuvo el éxito que merecía. Pasó desapercibida en su momento, y hoy es una rareza que solo los fans del anime más nostálgico recuerdan. Una película que merece ser redescubierta.",
    reel: "",
    related: [14, 18, 24]
}, {
    id: 17,
    title: "Megazone 23",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjOR_8j-P8IlQtxomqCMf5JP1EMHHJre7Y4uLBmEGvibVE_K97A1xKWatKAhpXE5BtOwohTxHcqZhcw3czuywc-dUfVh-Eo-E5yFdvU1Ki71rNs8YOIt_oZ7lisf89pO1YWd7Nas1Wv1FRargMKN4Pkh6Y5xKS0gOmprS2Bq7wDHACPb47bouFj-9SiEbsM=w282-h400",
    year: 1985,
    type: "OVA",
    duration: "80 min (Parte 1)",
    studio: "AIC / Artmic",
    director: "Noboru Ishiguro",
    genre: ["Ciencia ficción", "Cyberpunk", "Mecha"],
    tags: ["ciencia-ficción", "cyberpunk", "mecha", "robot", "experimental"],
    description: "Shogo descubre que su mundo es una simulación. Y la única forma de escapar es pilotando una moto que se transforma en robot. Sí, es tan genial como suena.",
    plot: "En el Tokio de 1985, Shogo es un joven biker que recibe una misteriosa motocicleta llamada Garland. Pronto descubre que la moto es en realidad un sistema de armas robótico, y que su mundo no es lo que parece. Perseguido por el ejército, Shogo se ve envuelto en una conspiración que lo llevará a descubrir la verdad sobre su realidad: vive en una simulación, y el mundo real está a punto de ser destruido.",
    analysis: "Megazone 23 es uno de los OVAs más influyentes de la historia. Su premisa (un mundo que resulta ser una simulación) fue la inspiración directa para 'The Matrix'. La animación es excelente, con diseños de personajes de Haruhiko Mikimoto (Macross) y una banda sonora de Shiro Sagisu (Evangelion). La historia es confusa y a veces incoherente, pero su estilo visual y su premisa la convierten en una obra imprescindible del cyberpunk.",
    forgotten: "Megazone 23 fue víctima de su propia ambición. Originalmente planeada como una serie de 26 episodios, fue cancelada y reducida a una OVA de 4 episodios. Además, su distribución internacional fue un desastre: Carl Macek la editó y la convirtió en 'Robotech: The Movie', un fracaso que apenas llegó a los cines. Solo una década después, Streamline Pictures la lanzó semi-propiamente, pero ya era demasiado tarde. Hoy es un clásico de culto, pero el público general la ha olvidado.",
    reel: "",
    related: [5, 19, 20]
}, {
    id: 18,
    title: "The Big O",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEj7-mkcswVVTnj1XM6Q5N4z_FqINV0df1k1EmEmDyB334sifXAk7fDYP4HPdczpBGavkXpo2oDM-avFm59b_CX3XUOQhFhqiH_83rjN3bKfrp3kqNZYL0QO6-LX3OTYCEuq_Ld9-9e_XmIGrFbApHbEnJVP6ifbo7WVNObLWI-TKyOJwv4fOeoeZ616koBK=w275-h400",
    year: 1999,
    type: "Serie",
    duration: "26 episodios",
    studio: "Sunrise",
    director: "Kazuyoshi Katayama",
    genre: ["Ciencia ficción", "Mecha", "Misterio"],
    tags: ["ciencia-ficción", "mecha", "robot", "misterio", "nocturno"],
    description: "Roger Smith es un negociador en una ciudad sin memoria. Y cuando las cosas se complican, pilota a Big O, un robot gigante que es la última esperanza de la ciudad.",
    plot: "En una ciudad donde nadie recuerda el pasado, Roger Smith se dedica a resolver conflictos como negociador. Pero cuando un nuevo misterio amenaza la ciudad, Roger debe pilotar a Big O para proteger a sus habitantes. La serie combina cine negro, mecha y misterio en una mezcla única.",
    analysis: "The Big O es una serie que combina cine negro, mecha y misterio en una mezcla única. La animación de Sunrise es excelente, y el diseño de personajes y escenarios es espectacular. La banda sonora de jazz y la ambientación art deco le dan un estilo inconfundible. Es una serie que merece ser vista por cualquier amante del anime.",
    forgotten: "Fue un fracaso en Japón, pero tuvo éxito moderado en Estados Unidos. Su cancelación tras la primera temporada fue un golpe duro para los fans, que lucharon por su regreso. La segunda temporada se produjo gracias a la presión de los fans estadounidenses, pero ya era demasiado tarde. Hoy es una serie de culto para los amantes del mecha y el misterio.",
    reel: "",
    related: [17, 19, 20]
}, {
    id: 19,
    title: "Video Girl Ai",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEgHIH47VvH-M1gWvURQLsKC5qaUObCRtjsshJ15IGIr3K9XA2YmQIWeqPnr2yChej1oNM5e1Jok0gH2cbv5SDHh1R2D4fBGI5DvLLQ4v1n9jcA1L4xZEah3tVDE12ECQ-gs7gEWldTY1PPXffxDO-uuWyOmz0XRhi_89Rls5bU22qYaxglnXgq2Ia2gxRVZ=w283-h400",
    year: 1992,
    type: "OVA",
    duration: "6 episodios",
    studio: "Production I.G",
    director: "Mitsuo Hashimoto",
    genre: ["Drama", "Romance", "Recuentos de la vida"],
    tags: ["drama", "romance", "recuentos", "nostálgico", "melancólico"],
    description: "Yota alquila un video. Y la chica de la pantalla cobra vida. Ai no es una actriz, es una chica virtual. Y está decidida a ayudar a Yota a conquistar a su crush. ¿El problema? Ai también se enamora de él.",
    plot: "Yota es un chico tímido que no sabe cómo declararse a su crush. Cuando alquila un video, la chica de la pantalla cobra vida. Ai es una chica virtual, diseñada para ayudar a los chicos a conquistar a sus amadas. Pero Ai también se enamora de Yota, y su misión se complica. Una historia de amor que trasciende la pantalla.",
    analysis: "Video Girl Ai es un OVA romántico con toque de fantasía. Production I.G demostró su maestría en la animación, con personajes que parecen cobrar vida. La historia es tierna y melancólica, y la música te atrapa desde el primer minuto. Es un clásico del anime romántico que merece ser redescubierto.",
    forgotten: "Es uno de esos OVAs que solo los más nostálgicos recuerdan. Su distribución fue limitada, y hoy es una rareza para los amantes del anime romántico. Una joya oculta que merece ser rescatada.",
    reel: "",
    related: [4, 16, 21]
}, {
    id: 20,
    title: "Onikirimaru (Ogre Slayer)",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEhfRTGVWMNjNA8FpktX5T-wcvHs_U4-3tNWudg5ZVTucAIWuQ-gLW5yBHzMSr_zUA2s7hV-cDX6LkmqQ_cDe_hjOU_SJvUpO4KQoUFXXUb8yOAGilBwEJ_dIHL6txNsaj77OzYV72uXNvMxkqKZTamI-ToIE4UkChVUoJuOkbsW-r-SUwr_8b-RdO31MN8N=w298-h400",
    year: 1994,
    type: "OVA",
    duration: "2 episodios",
    studio: "J.C.Staff",
    director: "Noboru Ishiguro",
    genre: ["Acción", "Fantasía oscura", "Samurái"],
    tags: ["acción", "fantasía", "samurái", "violento", "nocturno"],
    description: "Onikirimaru es un cazador de demonios en el Japón feudal. No tiene piedad, no tiene miedo, y no descansa hasta acabar con todos los demonios.",
    plot: "Onikirimaru es un cazador de demonios que viaja por el Japón feudal enfrentándose a criaturas mitológicas. Su misión es destruir a todos los demonios que amenazan a la humanidad. Pero su propia naturaleza es un misterio: ¿es humano, demonio o algo más?",
    analysis: "Onikirimaru es un OVA de acción con un protagonista estoico y violencia coreografiada. La animación es decente, y las escenas de lucha son trepidantes. Es una obra de culto para los amantes del anime de samuráis y fantasía oscura. Una joya oculta que merece ser redescubierta.",
    forgotten: "Su distribución fue muy limitada. Es una joya oculta para coleccionistas, pero el público general la ha olvidado. Una rareza que solo los fans más hardcore del anime de acción conocen.",
    reel: "",
    related: [10, 12, 17]
}, {
    id: 21,
    title: "Windaria",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEix78Fqbh6ik3yepcTAEvJbhsS8fCf-5WvKkmjmwN3Gd2Wn5lvQXtwvoVET_4AveNnJJTyRTF-bqlVJHFThCiWQFVH0cX68BCXFeZ8Vl_YwxKe_OgBFx6CoEucAYrSMFh4uRiRJCj6KsRIFkHVVmCXtGucaLDzB8qCK21k02oEOFa_lL9jngI1zBSdFQ_SV=w277-h400",
    year: 1986,
    type: "Película",
    duration: "100 min",
    studio: "Kaname Productions",
    director: "Kunihiko Yuyama",
    genre: ["Fantasía", "Aventura", "Romance"],
    tags: ["fantasía", "aventura", "romance", "melancólico", "nostálgico"],
    description: "Un granjero se ve envuelto en una guerra cuando su prometida es secuestrada. Pero la guerra no es lo que parece, y el amor no es suficiente para salvar el mundo.",
    plot: "En un reino de fantasía, un granjero llamado Izu se ve envuelto en una guerra cuando su prometida, Marin, es secuestrada. Izu se une al ejército para salvarla, pero pronto descubre que la guerra no es tan simple como parece. Los reinos están en conflicto, y la paz solo se logrará con un sacrificio.",
    analysis: "Windaria es una película de fantasía que mezcla romance, guerra y política. La animación es preciosa, y la historia está llena de momentos emotivos y épicos. Es una obra de culto para los amantes de la fantasía, pero el público general la ha olvidado.",
    forgotten: "Pasó sin pena ni gloria en su época. Su distribución fue limitada, y hoy es una joya oculta para los amantes de la fantasía. Una película que merece ser redescubierta.",
    reel: "",
    related: [1, 14, 24]
}, {
    id: 22,
    title: "Arion",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjflOQyYmr0mUc0DgavnTYtoq8WZsVPZoUxSil_E_DpnEIosOpHoLQd5ig_MTK36QSxp_7xm0chFK-Qa9_3t1Xchf0vkI_vDn5YZgqyW86yylJX6qlxdj-DaUIJSB5eD0najdCpx5o19JYwlQCUr1EBvJESP6NPTh4qcDrgZH1pdLedgL8OuKq1OjdHToLO=w283-h400",
    year: 1986,
    type: "Película",
    duration: "100 min",
    studio: "Sunrise",
    director: "Yoshikazu Yasuhiko",
    genre: ["Fantasía", "Aventura", "Mitología"],
    tags: ["fantasía", "aventura", "mitología", "épico", "color"],
    description: "Arion es un joven criado por los dioses. Busca venganza en la mitología griega. Pero los dioses no son tan justos como parece.",
    plot: "Arion es un joven criado por los dioses griegos. Su madre fue asesinada por los dioses, y Arion busca venganza. Emprende un viaje épico para enfrentarse a los dioses y descubrir la verdad sobre su origen. Una historia de mitología griega como nunca antes la habías visto.",
    analysis: "Arion es una epopeya de fantasía basada en la mitología griega. Sunrise demostró su maestría en la animación, con escenas de acción espectaculares y una historia épica. Es una obra de culto para los amantes de la mitología, pero el público general la ha olvidado.",
    forgotten: "Una de las películas más caras de su época, pero no tuvo éxito. Su distribución fue limitada, y hoy es una joya oculta para los amantes de la fantasía. Una película que merece ser redescubierta.",
    reel: "",
    related: [14, 21, 24]
}, {
    id: 23,
    title: "Black Magic M-66",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEj_JQF1VKs7ohoOf9H-qOwE-MKNgYMiviWa4RQ-9dHElRvKqhO_vtxU6pX3INQZWyqKWI9bX6ukJKQq0LbB3M-ij4a6u2eMvIc_rEPQJh9Ay928mZtwW8n9QK_5iJARujrlj9iAuiV2_BZswrQYJKDi4N-fwXTpPIhjeDgRTLFX6SGP3LWK_ESTi4oVru9G=w288-h400",
    year: 1987,
    type: "OVA",
    duration: "50 min",
    studio: "AIC / Animate",
    director: "Hiroyuki Kitakubo",
    genre: ["Ciencia ficción", "Acción", "Cyberpunk"],
    tags: ["ciencia-ficción", "acción", "cyberpunk", "robot", "violento"],
    description: "Un androide militar se vuelve loco. Una periodista debe detenerlo. Y la única forma de hacerlo es... destruyéndolo. Pero no es tan fácil.",
    plot: "El androide militar M-66 se vuelve loco y empieza a matar a todo lo que se mueve. Una periodista, que investigaba al ejército, se ve envuelta en la persecución. Su única esperanza es detener al androide antes de que cause más daños.",
    analysis: "Black Magic M-66 es pura acción cyberpunk de los 80. La animación es excelente, y las escenas de acción son trepidantes. Es una obra de culto para los amantes del cyberpunk, pero el público general la ha olvidado.",
    forgotten: "OVA que pasó desapercibido. Su distribución fue limitada, y hoy es una rareza para los amantes del cyberpunk. Una joya oculta que merece ser rescatada.",
    reel: "",
    related: [17, 19, 25]
}, {
    id: 24,
    title: "Armitage III",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEjejqPa2c9gRE5oU7rFQVumo-MG5qiVlolApDb8Lz1WQ_SvQe7LjuX0yWIaWlAgrejE06vDsxMzcaPm2qGbICOzJIdPppkImUmirNdBX67P29sCVZlxIWG1GDXpZBvxZqqPbGNOOhKt3q1-UqV6iF3dKLjskZtBQYzUqBERMoTWlfTl2aHabDLt-ti0Yl8t=w283-h400",
    year: 1995,
    type: "OVA",
    duration: "4 episodios",
    studio: "AIC",
    director: "Hiroyuki Ochi",
    genre: ["Ciencia ficción", "Cyberpunk", "Acción"],
    tags: ["ciencia-ficción", "cyberpunk", "acción", "robot", "futurista"],
    description: "En Marte, los androides llamados 'Terceros' son carne de cañón. Pero Armitage no es una máquina cualquiera: es policía, es mujer, y no se deja pisotear.",
    plot: "Naomi Armitage es una androide de tercera generación que trabaja como policía en Marte. Junto a su nuevo compañero humano, Ross Sylibus, investiga una serie de asesinatos de Terceros. Pronto descubren que el gobierno marciano está ocultando un oscuro secreto: los Terceros son mucho más que simples máquinas. Su creador, el doctor Asakura, buscaba crear el 'siguiente paso en la evolución humana', y Armitage es la pieza clave de su plan.",
    analysis: "Armitage III es el puente perfecto entre el cyberpunk de los 80 y el anime de acción de los 90. Chiaki J. Konaka (Serial Experiments Lain) escribió una historia que cuestiona qué significa ser humano, pero sin perder nunca el ritmo trepidante. La animación de AIC es de primera categoría, con diseños de personajes de Satoshi Urushihara que han envejecido como buen vino. Pero lo que la hace especial es su tono: es dura, cínica, pero con un corazón que late bajo el metal. Una joya que merece ser recordada.",
    forgotten: "Armitage III fue víctima de su propio éxito parcial: llegó a Occidente en una época en la que el cyberpunk ya estaba saturado (Ghost in the Shell, Akira, Bubblegum Crisis). Además, su OVA original de 4 episodios fue reeditada en dos películas que cambiaron su estructura, confundiendo a los fans. Su secuela 'Dual Matrix' fue un fracaso que manchó su reputación. Hoy es recordada solo por los que estábamos allí, pero los nuevos fans la ignoran.",
    reel: "https://video.fmga9-2.fna.fbcdn.net/o1/v/t2/f2/m412/AQOvjkLcaO4V4OdvsEhKTVkEGO8SJ1D8XqL7Oqo7B8xHgonQUTYFyEyapRRij0ZzoSSpIr4Tei1WrCJqAv7GXeeLNQmm1ueUpZWrIBd77A.mp4?_nc_cat=100&_nc_oc=Adp6gm0NdzHoGsQMk9jybSxOXgpQAsTxPjROaTanrxogleTrz-4jDWkBiIbaAQf6NhQ&_nc_sid=8bf8fe&_nc_ht=video.fmga9-2.fna.fbcdn.net&_nc_ohc=JaNq9qq8bWEQ7kNvwHzmMj0&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MTAyNjkzMjQxNjQ1OTE0MSwiYXNzZXRfYWdlX2RheXMiOjIxLCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6MTE4LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&_nc_gid=pzfC_bEBvVlQ9nECPgZ1sA&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQAqN7PY38Shz6Q40ijzP7FoEx9D-0PyYvEimU6V1Tcc3Q&oe=6A65A09E&bitrate=512006&tag=sve_sd",
    related: [23, 25, 17]
}, {
    id: 25,
    title: "Dragon's Heaven",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEh3BdhnmVIGfi82Jck-emi3yVcDwlg_Mwo6o03yrCBTt5NpHjnWaOgtMgKVKSs4fjCWiJ-JLeLgwIDqR2YOxX2XTzp0PwwrZmOpuz1gx3tulfV0klJPNsWNb9UKvot4WblVmu1-ZaQoTqI2hOGNypI1m6GOQBJOP_thWZWSGQgW1ci-BZgpFlbKCXl-h0Im=w267-h400",
    year: 1988,
    type: "OVA",
    duration: "1 episodio (40 minutos)",
    studio: "AIC",
    director: "Makoto Kobayashi",
    genre: ["Ciencia Ficción", "Mecha", "Post-apocalíptico"],
    tags: ["ciencia-ficción", "mecha", "robot", "post-apocalíptico", "experimental", "color"],
    description: "Una armadura robótica consciente despierta tras mil años. Y su única misión es proteger a su creador de un enemigo que no descansa.",
    plot: "La armadura Shaian despierta tras mil años de sueño. Su misión es proteger a su creador de Elmadine, un enemigo que ha esperado mil años para destruirlo. Una historia de ciencia ficción post-apocalíptica con un diseño visual espectacular.",
    analysis: "Dragon's Heaven es una obra maestra visual influenciada por el estilo de Moebius. Mezcla animación tradicional con maquetas y efectos especiales que te dejarán sin aliento. Es una de las mayores rarezas ocultas del anime de los 80, y una obra que merece ser vista por cualquier amante del anime.",
    forgotten: "Una de las mayores rarezas ocultas del anime de los 80. Su distribución fue limitadísima, y hoy es una joya oculta para coleccionistas. Una obra que merece ser redescubierta.",
    reel: "",
    related: [22, 24, 21]
}, {
    id: 26,
    title: "Call Me Tonight",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEiHPEopvDzhqnnHL_lvRjvfR8q8Ms25q9BQNlhszkndP3BA69WihVab7JAVgzIYM5VVV8voQ6vv86rL5uMnQaipzDFyudrUITav9KNYhE2EGBgmJa4TqGkfU21wXeOJswRAOrsUpYTrBMo7fsPXSiVArNiSC4Z7dgQ_Kb8Xd6aeW4BcBpidwTBih0MyqQmU=w273-h400",
    year: 1986,
    type: "OVA",
    duration: "1 episodio (35 minutos)",
    studio: "AIC",
    director: "Tatsuya Okamoto",
    genre: ["Comedia", "Romance", "Sobrenatural", "Ecchi", "Erótico"],
    tags: ["comedia", "romance", "sobrenatural", "ecchi", "erótico", "nostálgico", "oculto", "nocturno"],
    description: "Rumi es una succubus que trabaja en una agencia de acompañantes. Su trabajo: extraer energía masculina. Pero su nuevo cliente, un tímido oficinista, no es lo que parece.",
    plot: "Rumi trabaja en una agencia de acompañantes, pero en realidad es una succubus. Su trabajo consiste en extraer energía masculina de sus clientes. Todo va bien hasta que conoce a Akira, un oficinista que no se deja seducir fácilmente y que guarda un oscuro secreto.",
    analysis: "Call Me Tonight es una comedia romántica con toques sobrenaturales y ecchi. Mezcla el humor con situaciones absurdas y algo picantes. Tiene un ritmo ágil, diálogos ingeniosos y un diseño de personajes carismático. Es una rareza de los 80 que merece ser redescubierta.",
    forgotten: "Es una de esas OVAs que nunca tuvieron distribución internacional y hoy es prácticamente desconocida. Su temática y su estética la convierten en una joya oculta para los amantes del anime ochentero con humor adulto.",
    reel: "https://video.fmga9-3.fna.fbcdn.net/o1/v/t2/f2/m412/AQOw9D9C6CsmaXB7pu7kd3hGj_R7iQJezgBcqQKJYFhOAHHfO4sFeXykzBMWwJFrkT40fntqMqNzDzvTZfkAmBzrOzbk4_lY_LCYjUHgmw.mp4?_nc_cat=110&_nc_oc=AdqGRIckt0dcNQcdMk1-liSc8-AN5DMSKBL6YGeQ9mKm6qHF2UPK4zTpT-rSOos20ks&_nc_sid=8bf8fe&_nc_ht=video.fmga9-3.fna.fbcdn.net&_nc_ohc=HjNI4oQWijwQ7kNvwG8efHv&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MTMzODQ1NTU4MTA3MTc4NSwiYXNzZXRfYWdlX2RheXMiOjE3LCJ2aV91c2VjYXNlX2lkIjoxMDEyMiwiZHVyYXRpb25fcyI6NjgsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=cVLzrqJ3V16UykojMenGTQ&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQCpmZ6CY1u6NwJhDcyp2I296uQy_8lA2aPplJppOhOAJA&oe=6A66DBE4&bitrate=322490&tag=sve_sd",
    related: [21, 16, 4]
}, {
    id: 27,
    title: "Record of Lodoss War (OVA)",
    cover: "https://blogger.googleusercontent.com/img/a/AVvXsEhhViUktWqdMaH5IAy6mezha9dtNknBVGllR1FuQ4cbZXNTx0oB2iwem4A8b0QgyLizNV-YtiXvGPBW6UNr35a79gF6vWV5KrGVRg631qxTWX0wGsdPmZO34deUfWJ5f4ymaCYtRVlqDpHN6yG33z3qJw9y-SUWs7bf1jrlWRYch24A-fTxYHQVdqOVZ0sQ=w280-h400",
    year: 1990,
    type: "OVA",
    duration: "13 episodios (~25 min c/u)",
    studio: "Madhouse",
    director: "Akinori Nagaoka",
    genre: ["Fantasía", "Aventura", "Acción", "Épico"],
    tags: ["fantasía", "aventura", "acción", "épico", "nostálgico", "dragones"],
    description: "Parn y sus amigos se embarcan en una aventura para salvar a Lodoss de la oscuridad. Pero el destino de un reino no siempre es lo que parece.",
    plot: "Parn es un joven guerrero que sueña con ser un caballero. Cuando el continente de Lodoss se ve amenazado por las fuerzas del mal, Parn y sus amigos se embarcan en una aventura para salvar su mundo. Pero el mal no es tan simple como parece, y la verdad sobre la oscuridad es más compleja de lo que imaginan.",
    analysis: "Record of Lodoss War es una de las obras más influyentes del anime de fantasía. Madhouse demostró su maestría en la animación, con personajes inolvidables y una historia épica. La banda sonora y el diseño de personajes son espectaculares, y la serie es un clásico que todo amante de la fantasía debería ver.",
    forgotten: "Aunque es famosa en el anime de los 90, muchos fans nuevos no la conocen. Su distribución fue limitada fuera de Japón, y hoy es una joya para los amantes de la fantasía. Una serie que merece ser redescubierta por las nuevas generaciones.",
    episodios: 13,
    reel: "https://video.fmga9-2.fna.fbcdn.net/o1/v/t2/f2/m412/AQPrWZ_Lbxzkpwz35yEtc0_QFItiT9BKAddekxcER7XojKQCCh_TyXFabTy8mLEz6FiH1F4JCApNJD4IE_m2uICGZ3j7fMeOELetkmI42Q.mp4?_nc_cat=101&_nc_oc=AdqbyHi7FTbOl1sdS0IkuDnnCAQ98ybXydll6zIZn8SpvCwHWHLntxEvurcK3xLasls&_nc_sid=8bf8fe&_nc_ht=video.fmga9-2.fna.fbcdn.net&_nc_ohc=0rOQR2goAFYQ7kNvwGTAasP&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5GQUNFQk9PSy4uQzMuMzYwLnN2ZV9zZCIsInhwdl9hc3NldF9pZCI6MTM1MjU2MTI1MDM1MDQ4NiwiYXNzZXRfYWdlX2RheXMiOjMsInZpX3VzZWNhc2VfaWQiOjEwMTIyLCJkdXJhdGlvbl9zIjoxMjQsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&_nc_gid=h9U5Ck6r5aUmb_-pomtfvA&_nc_ss=7b2a8&_nc_zt=28&oh=00_AQAv3hhD1JfpD8GRMull01O9on9CUCKDnY8LManRUHbKZA&oe=6A672819&bitrate=388270&tag=sve_sd",
    related: [14, 21, 22]
}];
