// ============================================================
// live-action.js — 
// ============================================================
window.LIVE_ACTION_SLUGS = [
    "clarissa-lo-explica-todo",
    "el-hombre-nuclear",
    "eerie-indiana",
    "alf",
    "malcolm-el-de-en-medio",
    "el-tunel-del-tiempo",
    "sabrina-la-bruja-adolescente",
    "el-mundo-de-beakman",
    "cuentos-de-la-cripta",
    "lobo-del-aire",
    "starsky-y-hutch",
    "los-magni-ficos",
    "31-minutos",
    "le-temes-a-la-oscuridad",
    "la-peque-a-maravilla",
    "oshin",
    "dinosaurios",
    "las-nuevas-aventuras-de-flash-gordon",
    "el-vengador",
    "el-gladiador",
    "power-ranger-en-el-espacio",
    "power-ranger-fuerza-salvaje",
    "power-ranger-lost-galaxy",
    "power-ranger-mighty-morphin",
    "power-ranger-turbo",
    "power-ranger-zeo",
    "power-rangers-beast-morphers",
    "power-rangers-dino-charge",
    "power-rangers-dino-super-charge",
    "power-rangers-dino-trueno",
    "power-rangers-furia-animal",
    "power-rangers-lightspeed-rescue",
    "power-rangers-mega-force",
    "power-rangers-mystic-force",
    "power-rangers-rpm",
    "power-rangers-samurai",
    "power-rangers-spd",
    "power-rangers-super-mega-force",
    "power-rangers-super-ninja-steel",
    "power-rangers-time-force",
    "power-rangers-tormenta-ninja",
    "ultraman"
];
