// ============================================================
// series-rotas.js
// Formato: "api:slug" — api puede ser "retrotve", "hen-api", "local"
// ============================================================

window.SERIES_ROTAS = [
    // ---------- RETROTVE (de tu escaneo) ----------
    "retrotve:space-academy",
    "retrotve:aprendiendo-a-vivir",
    "retrotve:aquaman",
    "retrotve:astroboy-1980",
    "retrotve:atom-man-vs-superman",
    "retrotve:automan",
    "retrotve:aventureros-del-aire",
    "retrotve:las-aventuras-de-batman",
    "retrotve:batman-del-futuro",
    "retrotve:batman-la-serie-animada-1997",
    "retrotve:batman-la-serie-animada",
    "retrotve:battlestar-galactica",
    "retrotve:beverly-hills-90210",
    "retrotve:blanco-y-negro",
    "retrotve:dumb-and-dumber",
    "retrotve:buck-rogers-en-el-siglo-25",
    "retrotve:burst-angel",
    "retrotve:chips",
    "retrotve:ci5-los-profesionales",
    "retrotve:cadillacs-and-dinosaurios",
    "retrotve:calabozos-y-dragones",
    "retrotve:highway-to-heaven",
    "retrotve:candy-candy",
    "retrotve:captain-america",
    "retrotve:centennial",
    "retrotve:chip-y-dale-al-rescate",
    "retrotve:chuck-norris-karate-kommando",
    "retrotve:columbo",
    "retrotve:espacio-1999",
    "retrotve:cuentos-asombrosos",
    "retrotve:dartacan-y-los-tres-mosqueperros",
    "retrotve:dna",
    "retrotve:daktari",
    "retrotve:danny-phantom-lat",
    "retrotve:daria",
    "retrotve:digimon-adventure",
    "retrotve:dino-boy-en-el-valle-perdido",
    "retrotve:dino-riders",
    "retrotve:don-gato-y-su-pandilla",
    "retrotve:los-persuasores",
    "retrotve:dragon-ball-gt",
    "retrotve:dias-felices",
    "retrotve:el-avispon-verde",
    "retrotve:el-critico",
    "retrotve:el-equipo-de-los-super-poderosos-guardianes-galacticos",
    "retrotve:el-escuadron-del-tiempo",
    "retrotve:el-gallo-claudio",
    "retrotve:drak-pack",
    "retrotve:el-increible-hulk-1978",
    "retrotve:el-invencible-iron-man",
    "retrotve:the-mighty-thor-1966",
    "retrotve:el-pulpo-manotas",
    "retrotve:el-santo",
    "retrotve:el-show-de-ren-y-stimpy",
    "retrotve:speed-buggy",
    "retrotve:el-trio-galaxia",
    "retrotve:el-tunel-del-tiempo",
    "retrotve:el-valle-de-los-dinosaurios",
    "retrotve:el-zorro",
    "retrotve:zorro-la-serie-animada",
    "retrotve:el-crucero-del-amor",
    "retrotve:el-gran-chaparral",
    "retrotve:el-planeta-de-los-simios",
    "retrotve:el-resplandor",
    "retrotve:el-reto-de-los-super-amigos",
    "retrotve:el-show-de-scooby-doo-y-scrappy-doo",
    "retrotve:el-show-de-super-mario-bros",
    "retrotve:escuela-de-heroes",
    "retrotve:fantasma-2040",
    "retrotve:fantasma-del-espacio",
    "retrotve:fish-police",
    "retrotve:the-flash-gordon-serial-1936",
    "retrotve:frankenstein-jr",
    "retrotve:galactica-1980",
    "retrotve:night-gallery",
    "retrotve:ginger",
    "retrotve:gran-mazinger",
    "retrotve:he-man-y-los-masters-del-universo1",
    "retrotve:heathcliff",
    "retrotve:heidi",
    "retrotve:hellsing",
    "retrotve:hong-kong-phooey",
    "retrotve:hercules",
    "retrotve:iron-man-la-serie-animada",
    "retrotve:jim-west",
    "retrotve:jonny-quest",
    "retrotve:josie-y-las-melodicas-en-el-espacio",
    "retrotve:josie-y-sus-gatimelodicas",
    "retrotve:the-karate-kid",
    "retrotve:kenan-kel",
    "retrotve:kolchak-the-night-stalker",
    "retrotve:kung-fu",
    "retrotve:la-dimension-desconocida",
    "retrotve:la-familia-addams-1973",
    "retrotve:la-isla-de-gilligan",
    "retrotve:la-isla-del-tesoro",
    "retrotve:la-mujer-maravilla",
    "retrotve:salems-lot",
    "retrotve:el-show-de-la-pantera-rosa",
    "retrotve:la-tonta-bruja",
    "retrotve:la-chica-de-cipol",
    "retrotve:la-hormiga-y-el-oso-hormiguero",
    "retrotve:la-isla-de-la-fantasia",
    "retrotve:la-vuelta-al-mundo-en-ochenta-dias",
    "retrotve:ladron-sin-destino",
    "retrotve:las-nuevas-aventuras-de-flash-gordon",
    "retrotve:las-tortugas-ninja",
    "retrotve:las-aventuras-de-ricky-ricon",
    "retrotve:las-aventuras-de-los-osos-gummi",
    "retrotve:las-calles-de-san-francisco",
    "retrotve:las-nuevas-aventuras-de-batman",
    "retrotve:la-sirenita",
    "retrotve:las-nuevas-peliculas-de-scooby-doo",
    "retrotve:las-olimpiadas-de-la-risa",
    "retrotve:lindo-pulgoso",
    "retrotve:lobo-del-aire",
    "retrotve:loonatics",
    "retrotve:fantastic-four-1967",
    "retrotve:los-caballeros-arabes",
    "retrotve:los-campeones-mighty-ducks",
    "retrotve:centinelas-del-espacio",
    "retrotve:the-centurions",
    "retrotve:dinoplativolos",
    "retrotve:los-dukes-de-hazzard",
    "retrotve:los-halcones-galacticos",
    "retrotve:los-herculoides",
    "retrotve:the-impossibles",
    "retrotve:los-invasores",
    "retrotve:la-familia-addams",
    "retrotve:los-magnificos",
    "retrotve:los-osos-montaneses",
    "retrotve:los-picapiedra",
    "retrotve:los-soprano",
    "retrotve:los-super-globetrotters",
    "retrotve:los-tres-chiflados",
    "retrotve:los-cuentos-de-la-calle-broca",
    "retrotve:los-invencibles-de-nemesis",
    "retrotve:los-miserables",
    "retrotve:los-supersonicos",
    "retrotve:los-angeles-de-charlie",
    "retrotve:macgyver",
    "retrotve:malcolm-el-de-en-medio",
    "retrotve:mandibulin",
    "retrotve:matrimonio-con-hijos",
    "retrotve:meteoro",
    "retrotve:mi-bella-genio",
    "retrotve:micro-ventures",
    "retrotve:mighty-morphin-alien-rangers",
    "retrotve:mike-lu-og",
    "retrotve:monk",
    "retrotve:mork-mindy",
    "retrotve:the-sub-mariner",
    "retrotve:paso-a-paso",
    "retrotve:perdidos-en-el-espacio",
    "retrotve:popeye-and-son",
    "retrotve:remi-el-nino-de-nadie",
    "retrotve:robocop",
    "retrotve:robotech",
    "retrotve:roma",
    "retrotve:sabrina-la-bruja-adolecente",
    "retrotve:sailor-moon",
    "retrotve:sam-y-cat",
    "retrotve:sexo-en-la-ciudad1",
    "retrotve:shaka-zulu",
    "retrotve:shazzan",
    "retrotve:shogun",
    "retrotve:silver-surfer",
    "retrotve:martillo-hammer",
    "retrotve:spider-man-y-sus-sorprendentes-amigos",
    "retrotve:spiderman-unlimited",
    "retrotve:star-trek-la-serie-animada",
    "retrotve:star-wars-droids-las-aventuras-de-r2d2-y-c3po",
    "retrotve:star-wars-clone-wars-2003",
    "retrotve:star-wars-the-clone-wars",
    "retrotve:starsky-y-hutch",
    "retrotve:super-agente-cobra",
    "retrotve:super-mario-bros-3",
    "retrotve:superboy",
    "retrotve:superman-hermanos-fleischer",
    "retrotve:t-j-hooker",
    "retrotve:tarzan-el-senor-de-la-selva",
    "retrotve:batman-serial-1943",
    "retrotve:thundarr-el-barbaro",
    "retrotve:tiro-loco-mcgraw",
    "retrotve:tom-jerry",
    "retrotve:transformers",
    "retrotve:un-cachorro-llamado-scooby-doo",
    "retrotve:v-invasion-extraterrestre",
    "retrotve:viaje-al-fondo-del-mar",
    "retrotve:voyagers",
    "retrotve:quantum-leap",
    "retrotve:walker-ranger-de-texas",
    "retrotve:wildc-a-t-s",
    "retrotve:hola-sandy-bell",
    "retrotve:whos-the-boss",

    // ---------- HEN-API ----------
    // "hen-api:algun-slug-roto",

    // ---------- LOCALES ----------
    "local:dragon-quest-las-aventuras-de-fly",
    "local:voltron",
    "local:battle-commander-daimos",
    "local:macros-zero",
    "local:bionic-six",
    "local:las-nuevas-aventuras-de-he-man",
    "local:ren-y-stimpy",
    "local:la-princesa-de-los-mil-an-os",
    "local:dragon-ball-super",
    "local:dragon-ball",
    "local:dragon-ball-z",
    "local:saint-seiya-omega",
    "local:saint-seiya-soul-of-gold",
    "local:saintia-sho",
    "local:hunter-x-hunter",
    "local:berserk",
    "local:zoids",
    "local:yu-yu-hakusho",
    "local:utena",
    "local:ojos-de-gato",
    "local:espiritu-de-lucha",
    "local:power-rangers-dino-trueno",
    "local:slam-dunk",
    "local:sailor-moon",
    "local:kurochan",
    "local:sailor-moon-crystal",
    "local:los-centuriones",
    "local:capitan-futuro",
    "local:super-agente-cobra",
    "local:marco",
    "local:la-abeja-maya",
    "local:remi-el-nino-de-nadie",
    "local:las-guerreras-magicas",
];

// ------------------------------------------------------------
// Helper: ¿esta obra específica está rota?
// ------------------------------------------------------------
window.estaRota = function (obra) {
    if (!obra || !window.SERIES_ROTAS) return false;

    let api = "local";
    const url = obra.apiUrl || "";
    if (url.includes("retrotve")) api = "retrotve";
    else if (url.includes("hen-api")) api = "hen-api";

    const slug = obra.apiSlug || obra.slug || null;
    if (!slug) return false;

    return window.SERIES_ROTAS.includes(`${api}:${slug}`);
};
